name: Build Nelotsavam APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.18.0'
        
    - name: Setup Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Verify environment
      run: |
        node --version
        npm --version
        java -version
        
    - name: Clean install dependencies
      run: |
        rm -rf node_modules package-lock.json
        npm install
      
    - name: Build Next.js app
      run: |
        npm run build
        ls -la
        echo "Contents of out directory:"
        ls -la out/ || echo "out directory not found"
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
        
    - name: Initialize Capacitor if needed
      run: |
        if [ ! -d "android" ]; then
          npx cap add android
        fi
        
    - name: Sync Capacitor
      run: |
        npx cap sync android
        
    - name: Make gradlew executable
      run: chmod +x android/gradlew
      
    - name: Clean and build APK
      run: |
        cd android
        ./gradlew clean
        ./gradlew assembleDebug --no-daemon --console=plain --stacktrace
        
    - name: Verify APK exists
      run: |
        echo "Looking for APK files:"
        find android -name "*.apk" -type f
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: nelotsavam-debug-apk
        path: android/app/build/outputs/apk/debug/*.apk
        retention-days: 30
